name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:${{ github.sha }} ./expensy_frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensy_frontend:${{ github.sha }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:${{ github.sha }} ./expensy_backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/expensy_backend:${{ github.sha }}
